export const VOCABULAR = {
    id: 'ID',
    inn: 'ИНН',
    kpp: 'КПП',
    name: 'ФИО',
    ogrn: 'ОГРН',
    type: 'Тип',
    emails: 'Почта',
    phones: 'Телефон',
    address: 'Адрес',
    website: 'Сайт',
    director:'Директор',
    bank_name: 'Имя банка',
    created_at: 'Дата создания',
    updated_at: 'Дата редактирования',
    type_director: 'В лице',
    payment_account: 'Лицевой счет',
    correspondent_account: 'Корреспондентский счет',
    reference_company_status_id: 'Статус компании',
    reference_service_property_name: 'Наименование свойства услуги',
    order_service_name: 'Наименование услуги',
    created: 'Создано',
    updated: 'Обновлено',
    deleted: 'Удалено',
    lead_fio: 'ФИО',
    lead_email: 'Почта',
    lead_phone: 'Телефон',
    creator_user_name: 'ФИО создателя',
    creator_user_position: 'Позиция создателя',
    sales_manager_user_name: 'Менеджер SALES',
    sales_manager_user_position: 'Позиция менеджера',
    value: 'Значение',
    company_name: 'Наименование компании',
    reference_sources_name: 'Источник клиента',
    reference_order_type_name: 'Тип процедуры',
    receive_datetime: 'Дата получения заявки',
    processing_end_datetime: 'Дата отработки заявки'
}